ARG RUBY_VERSION=3.3.11
FROM ruby:$RUBY_VERSION-slim

RUN apt-get update -qq && \
    apt-get install -y build-essential libpq-dev nodejs npm curl git --no-install-recommends && \
    npm install -g yarn && \
    gem install foreman && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /rails

ENV RAILS_ENV=development

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

RUN chmod +x bin/dev bin/docker-entrypoint

EXPOSE 3000

CMD ["./bin/dev"]
